---
- hosts: all
  tasks:
    - name: Ensure a file exists with specific content
      copy:
        dest: /tmp/ansible_teste_file.txt
        content: |
          This is a teste file
          Managed by Ansible.
          owner: root
          group: root
          mode: '0644'

    - name: Ensure a line is present in a configuration file
      lineinfile:
        path: /tmp/ansible_teste_confiq.conf
        line: 'ConfigOption=True'