---
- name: File Managemente Playbook
  hosts: all

  tasks:
    - name: Cria um arquivo vazio
      ansible.builtin.file:
        path: /tmp/empty_file.txt
        state: touch
      register: result_empty_file.changed

    - debug:
        msg: "Empty file create successfully"
      when: result_empty_file.changed

    - name: Cria um arquivo de texto
      ansible.builtin.copy:
        content: Aqui é o que esta escrito dentro do arquivo.
        dest: /tmp/text_file.txt
      register: result_text_file

    - debug:
        msg: "Text file created successfully"
      when: result_text_file.changed

    - name: Verificar se o Arquivo Existe
      ansible.builtin.stat:
        path: /tmp/empty_file.txt
      register: file_stat

    - debug:
        msg: "O Texto existe"
      when: file_stat.stat.exists

    - name: Mudança de permissão do arquivo
      ansible.builtin.file:
        path: /tmp/text_file.txt
        mode: '0600'
      register: result_change_permission

    - debug:
        msg: "file permission change successfully"
      when: result_change_permission.changed

    - name: Delete o arquivo se ele existe"
      ansible.builtin.file:
        path: /tmp/unwanted_file.txt
        state: absent
      register: result_delete_file

    - debug:
        msg: "Arquivo deletado com sucesso"
      when: result_delete_file.changed


